"""
Watchlist configuration.

At startup the app fetches the S&P 500, S&P 400 MidCap, and S&P 600 SmallCap
component lists from Wikipedia (~1,500 US-listed large/mid/small caps), merges
them with a curated list of ~300 international blue-chips that trade on US
exchanges (ADRs or direct listings), and caches the result locally for 7 days.

If the network is unavailable the international list is used as a fallback.
"""

import json
import logging
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Alert threshold ────────────────────────────────────────────────────────
DROP_THRESHOLD_PCT = 10.0

# ── Cache ──────────────────────────────────────────────────────────────────
_CACHE_FILE = Path(__file__).parent / ".watchlist_cache.json"
_CACHE_MAX_AGE = timedelta(days=7)

# ── S&P index Wikipedia sources ────────────────────────────────────────────
_SP_SOURCES = [
    {
        "url": "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
        "label": "S&P 500",
    },
    {
        "url": "https://en.wikipedia.org/wiki/List_of_S%26P_400_companies",
        "label": "S&P 400",
    },
    {
        "url": "https://en.wikipedia.org/wiki/List_of_S%26P_600_companies",
        "label": "S&P 600",
    },
]

# ── Curated international blue-chips (ADRs / direct US-exchange listings) ─
# These are large, reputable companies from outside the US that trade on NYSE,
# NASDAQ, or well-covered OTC markets and are reliably available in yfinance.
_INTERNATIONAL: dict[str, str] = {
    # ── United Kingdom ────────────────────────────────────────────────────
    "SHEL":  "Shell plc (UK)",
    "AZN":   "AstraZeneca (UK)",
    "BP":    "BP plc (UK)",
    "GSK":   "GSK plc (UK)",
    "BTI":   "British American Tobacco (UK)",
    "BCS":   "Barclays (UK)",
    "LYG":   "Lloyds Banking Group (UK)",
    "UL":    "Unilever (UK/Netherlands)",
    "VOD":   "Vodafone Group (UK)",
    "NGG":   "National Grid (UK)",
    "RIO":   "Rio Tinto (UK/Australia)",
    "ICLR":  "ICON plc (Ireland)",
    "ACCD":  "Accolade (UK)",          # placeholder — swap if needed
    "EXPGY": "Experian (Ireland/UK)",
    "RELX":  "RELX plc (UK)",
    "PSON":  "Pearson (UK)",
    # ── Netherlands ───────────────────────────────────────────────────────
    "ASML":  "ASML Holding (Netherlands)",
    "ING":   "ING Groep (Netherlands)",
    "PHG":   "Philips (Netherlands)",
    # ── Germany ───────────────────────────────────────────────────────────
    "DB":    "Deutsche Bank (Germany)",
    "SAP":   "SAP SE (Germany)",
    "SIEGY": "Siemens AG (Germany)",
    "BMWYY": "BMW AG (Germany)",
    "MBGYY": "Mercedes-Benz Group (Germany)",
    "BAYRY": "Bayer AG (Germany)",
    "BASFY": "BASF SE (Germany)",
    "DTEGY": "Deutsche Telekom (Germany)",
    "ALIZY": "Allianz SE (Germany)",
    "MURGY": "Münchener Rückversicherung / Munich Re (Germany)",
    "VWAGY": "Volkswagen AG (Germany)",
    "POAHY": "Porsche Automobil Holding (Germany)",
    "ADDYY": "adidas AG (Germany)",
    "HEI":   "Heidelberg Materials (Germany)",   # NYSE listed
    "RWEOY": "RWE AG (Germany)",
    "EONGY": "E.ON SE (Germany)",
    "DHLGY": "Deutsche Post / DHL Group (Germany)",
    "XTRAGY":"Covestro (Germany)",
    # ── France ────────────────────────────────────────────────────────────
    "TTE":   "TotalEnergies (France)",
    "SNY":   "Sanofi (France)",
    "EADSY": "Airbus SE (France/Europe)",
    "BNPQY": "BNP Paribas (France)",
    "LRLCY": "L'Oréal (France)",
    "LVMUY": "LVMH Moët Hennessy Louis Vuitton (France)",
    "HESAY": "Hermès International (France)",
    "DANOY": "Danone (France)",
    "SGBLY": "Société Générale (France)",
    "CRARY": "Crédit Agricole (France)",
    "AXAHY": "AXA SA (France)",
    "ENGIEY":"Engie (France)",
    "ORANF": "Orange SA (France)",
    "KERRY": "Kering (France)",
    "PUBGY": "Publicis Groupe (France)",
    "MLCO":  "Melco Resorts (Macau/France-listed parent)",
    "SBGSY": "Schneider Electric (France)",
    "CAPLF": "Capgemini (France)",
    "AIVAF": "Air Liquide (France)",
    "VIEIF": "Vivendi (France)",
    # ── Switzerland ───────────────────────────────────────────────────────
    "UBS":   "UBS Group AG (Switzerland)",
    "NVS":   "Novartis AG (Switzerland)",
    "NSRGY": "Nestlé SA (Switzerland)",
    "RHHBY": "Roche Holding AG (Switzerland)",
    "ABB":   "ABB Ltd (Switzerland)",
    "LOGI":  "Logitech International (Switzerland)",
    "ZURVY": "Zurich Insurance Group (Switzerland)",
    "CSGNY": "Swiss Re AG (Switzerland)",
    "GEBN":  "Geberit AG (Switzerland)",
    "SGSOY": "SGS SA (Switzerland)",
    "GFORY": "Georg Fischer AG (Switzerland)",
    # ── Scandinavia ───────────────────────────────────────────────────────
    "NVO":   "Novo Nordisk A/S (Denmark)",
    "EQNR":  "Equinor ASA (Norway)",
    "ERIC":  "Ericsson (Sweden)",
    "NOK":   "Nokia Oyj (Finland)",
    "NNDNF": "Neste Oyj (Finland)",
    "ATLCY": "Atlas Copco AB (Sweden)",
    "VOLVY": "Volvo AB (Sweden)",
    "HVOLF": "Husqvarna AB (Sweden)",
    "DNSKF": "Danske Bank (Denmark)",
    "NDVLY": "Novozymes (Denmark)",
    "ORSTED":"Ørsted A/S (Denmark)",
    "SMNEY": "Sampo Oyj (Finland)",
    # ── Spain ─────────────────────────────────────────────────────────────
    "SAN":   "Banco Santander (Spain)",
    "BBVA":  "BBVA (Spain)",
    "TEF":   "Telefónica (Spain)",
    "IDEXY": "Industria de Diseño Textil / Inditex (Spain)",
    "REPYY": "Repsol (Spain)",
    "IBDRY": "Iberdrola SA (Spain)",
    "ACSAY": "ACS Group (Spain)",
    "CLNX":  "Cellnex Telecom (Spain)",
    # ── Italy ─────────────────────────────────────────────────────────────
    "ENLAY": "Enel SpA (Italy)",
    "STM":   "STMicroelectronics (Italy/France)",
    "ENEL":  "Enel SpA (Italy)",
    "ENIOY": "Eni SpA (Italy)",
    "UNCRY": "UniCredit SpA (Italy)",
    "ISPZY": "Intesa Sanpaolo (Italy)",
    "PIAGF": "Piagio (Italy)",
    "EXAHY": "Exor (Italy)",
    # ── Belgium / Luxembourg ──────────────────────────────────────────────
    "ANHUY": "Anheuser-Busch InBev (Belgium)",
    "UCB":   "UCB SA (Belgium)",
    "AGLXY": "ageas (Belgium)",
    # ── Australia ─────────────────────────────────────────────────────────
    "BHP":   "BHP Group (Australia)",
    "WDS":   "Woodside Energy (Australia)",
    "CBAUY": "Commonwealth Bank of Australia",
    "NABZY": "National Australia Bank",
    "ANZGY": "ANZ Banking Group (Australia)",
    "WBCOY": "Westpac Banking (Australia)",
    "MQBKY": "Macquarie Group (Australia)",
    "NCMGY": "Newcrest Mining (Australia)",
    "BXBLY": "Brambles Ltd (Australia)",
    "RMDX":  "ResMed Inc (Australia/US)",   # NYSE listed
    "AMCRY": "Amcor plc (Australia/UK)",
    "ATLAX": "Atlassian (Australia/US)",    # TEAM on NASDAQ
    "TEAM":  "Atlassian Corporation (Australia/US)",
    # ── Japan ─────────────────────────────────────────────────────────────
    "TM":    "Toyota Motor Corporation (Japan)",
    "SONY":  "Sony Group Corporation (Japan)",
    "HMC":   "Honda Motor Co (Japan)",
    "MUFG":  "Mitsubishi UFJ Financial Group (Japan)",
    "SMFG":  "Sumitomo Mitsui Financial Group (Japan)",
    "MFG":   "Mizuho Financial Group (Japan)",
    "NTT":   "Nippon Telegraph & Telephone (Japan)",
    "TOELY": "Tokyo Electron Ltd (Japan)",
    "HTHIY": "Hitachi Ltd (Japan)",
    "FANUY": "Fanuc Corporation (Japan)",
    "DSNKY": "Daikin Industries (Japan)",
    "PCRFY": "Panasonic Holdings (Japan)",
    "SSDOY": "Shin-Etsu Chemical (Japan)",
    "KDDIY": "KDDI Corporation (Japan)",
    "SBCFF": "SoftBank Corp (Japan)",
    "SFTBY": "SoftBank Group (Japan)",
    "NTDOY": "Nintendo Co Ltd (Japan)",
    "CNTFY": "Canon Inc (Japan)",
    "SEKEY": "Seiko Epson (Japan)",
    "BRDCY": "Bridgestone Corporation (Japan)",
    "DNZOF": "Denso Corporation (Japan)",
    "ROHCY": "Rohm Co Ltd (Japan)",
    "KYOCY": "Kyocera Corporation (Japan)",
    "MRAAF": "Murata Manufacturing (Japan)",
    "AJINY": "Ajinomoto (Japan)",
    "FUJIY": "Fujifilm Holdings (Japan)",
    "OKSNY": "Olympus Corporation (Japan)",
    "NISTF": "Nissan Motor (Japan)",
    "MZDAY": "Mazda Motor (Japan)",
    "SSUMY": "Subaru Corporation (Japan)",
    "ISUZY": "Isuzu Motors (Japan)",
    "YAMCY": "Yamaha Motor (Japan)",
    "KWHIY": "Kawasaki Heavy Industries (Japan)",
    "NDEKY": "Nippon Steel (Japan)",
    "MITSY": "Mitsui & Co (Japan)",
    "MSBHY": "Mitsubishi Corporation (Japan)",
    "ITOCY": "Itochu Corporation (Japan)",
    "MARUY": "Marubeni Corporation (Japan)",
    "SSUNF": "Sumitomo Corporation (Japan)",
    "THKLY": "THK Co (Japan)",
    # ── South Korea ───────────────────────────────────────────────────────
    "PKX":   "POSCO Holdings (South Korea)",
    "KB":    "KB Financial Group (South Korea)",
    "SHG":   "Shinhan Financial Group (South Korea)",
    "WF":    "Woori Financial Group (South Korea)",
    "SSNLF": "Samsung Electronics (South Korea)",
    "LGCLF": "LG Chem (South Korea)",
    "HYMTF": "Hyundai Motor (South Korea)",
    "HXSCL": "Hyundai Mobis (South Korea)",
    "SKLKF": "SK Hynix (South Korea)",
    "XIACF": "NAVER Corporation (South Korea)",
    "KIAOF": "Kia Corporation (South Korea)",
    # ── Taiwan ────────────────────────────────────────────────────────────
    "TSM":   "Taiwan Semiconductor Manufacturing (Taiwan)",
    "UMC":   "United Microelectronics (Taiwan)",
    "ASX":   "ASE Technology Holding (Taiwan)",
    # ── China / Hong Kong (ADRs) ─────────────────────────────────────────
    "BABA":  "Alibaba Group Holding (China)",
    "TCEHY": "Tencent Holdings (China)",
    "JD":    "JD.com (China)",
    "PDD":   "PDD Holdings (China)",
    "BIDU":  "Baidu Inc (China)",
    "NTES":  "NetEase Inc (China)",
    "BEKE":  "KE Holdings (China)",
    "ZTO":   "ZTO Express (China)",
    "YUMC":  "Yum China Holdings (China)",
    "BZ":    "Kanzhun / BOSS Zhipin (China)",
    "MNSO":  "MINISO Group (China)",
    "VNET":  "VNET Group (China)",
    "LI":    "Li Auto (China)",
    "NIO":   "NIO Inc (China)",
    "XPEV":  "XPeng Inc (China)",
    "RERE":  "ATRenew (China)",
    "CANG":  "Cango Inc (China)",
    "TIGR":  "UP Fintech Holding (China)",
    "MPNGY": "Man Wah Holdings (China/HK)",
    # ── India ─────────────────────────────────────────────────────────────
    "HDB":   "HDFC Bank (India)",
    "INFY":  "Infosys Ltd (India)",
    "WIT":   "Wipro Ltd (India)",
    "IBN":   "ICICI Bank (India)",
    "ICICIF":"ICICI Bank (India alt ticker)",
    "SIFY":  "Sify Technologies (India)",
    "RECON": "Recon Technology (China/India)",
    "RDY":   "Dr. Reddy's Laboratories (India)",
    "CIPLA": "Cipla (India)",            # listed on NSE/BSE; OTC in US
    "HCLT":  "HCL Technologies (India)",
    "TATAF": "Tata Consultancy Services (India)",
    "MBFJF": "Mahindra & Mahindra (India)",
    # ── Canada ────────────────────────────────────────────────────────────
    "RY":    "Royal Bank of Canada",
    "TD":    "Toronto-Dominion Bank",
    "BNS":   "Bank of Nova Scotia",
    "BMO":   "Bank of Montreal",
    "CM":    "Canadian Imperial Bank of Commerce (CIBC)",
    "MFC":   "Manulife Financial Corporation",
    "SLF":   "Sun Life Financial",
    "GWO":   "Great-West Lifeco",
    "CNI":   "Canadian National Railway",
    "CP":    "Canadian Pacific Kansas City",
    "CNQ":   "Canadian Natural Resources",
    "SU":    "Suncor Energy",
    "IMO":   "Imperial Oil",
    "NTR":   "Nutrien Ltd",
    "SHOP":  "Shopify Inc",
    "BCE":   "BCE Inc",
    "TU":    "TELUS Corporation",
    "ENB":   "Enbridge Inc",
    "TRP":   "TC Energy Corporation",
    "BAM":   "Brookfield Asset Management",
    "BN":    "Brookfield Corporation",
    "TFII":  "TFI International",
    "WCN":   "Waste Connections",
    "CAE":   "CAE Inc",
    "QSR":   "Restaurant Brands International",
    "TECK":  "Teck Resources",
    "FM":    "First Quantum Minerals",
    "CCO":   "Cameco Corporation",
    "AGI":   "Alamos Gold",
    "K":     "Kinross Gold",
    "ABX":   "Barrick Gold (listed as GOLD on NYSE)",
    "GOLD":  "Barrick Gold Corporation",
    "WPM":   "Wheaton Precious Metals",
    "EQB":   "EQB Inc",
    "POW":   "Power Corporation of Canada",
    "MG":    "Magna International",
    "ONEX":  "Onex Corporation",
    "BYD":   "Boyd Group Services",
    "LSPD":  "Lightspeed Commerce",
    "DNTL":  "Dentalcorp Holdings",
    "AFRM":  "Affirm Holdings (US but notable)",  # already S&P if large enough
    # ── Brazil ────────────────────────────────────────────────────────────
    "VALE":  "Vale SA (Brazil)",
    "ITUB":  "Itaú Unibanco Holding (Brazil)",
    "BBD":   "Banco Bradesco (Brazil)",
    "PBR":   "Petróleo Brasileiro / Petrobras (Brazil)",
    "ABEV":  "Ambev SA (Brazil)",
    "BSBR":  "Banco Santander Brasil",
    "GGBR4": "Gerdau SA (Brazil)",
    "BRFS":  "BRF SA (Brazil)",
    "CIG":   "Companhia Energética de Minas Gerais (Brazil)",
    "GGB":   "Gerdau SA (Brazil)",
    "ELP":   "Centrais Elétricas Brasileiras (Brazil)",
    "ERJ":   "Embraer SA (Brazil)",
    "SBSP3": "Sabesp (Brazil)",          # might not be US-listed
    # ── Latin America ─────────────────────────────────────────────────────
    "SQM":   "Sociedad Química y Minera de Chile",
    "MELI":  "MercadoLibre Inc (Argentina/Uruguay)",
    "EC":    "Ecopetrol SA (Colombia)",
    "AMX":   "América Móvil SAB de CV (Mexico)",
    "GMEXICOB": "Grupo México (Mexico)",
    "WALMEX":"Walmart de México (Mexico)",
    "GFNORTEO": "Grupo Financiero Banorte (Mexico)",
    "FEMSAUBD": "FEMSA (Mexico)",
    "FMX":   "Fomento Económico Mexicano / FEMSA (Mexico)",
    # ── Israel ────────────────────────────────────────────────────────────
    "NICE":  "NICE Systems (Israel)",
    "CHKP":  "Check Point Software Technologies (Israel)",
    "CYBR":  "CyberArk Software (Israel)",
    "MNDY":  "monday.com (Israel)",
    "WIX":   "Wix.com (Israel)",
    "GLBE":  "Global-E Online (Israel)",
    "NVCR":  "NovoCure Ltd (Israel)",
    "TEVA":  "Teva Pharmaceutical Industries (Israel)",
    "ESLT":  "Elbit Systems (Israel)",
    "CEVA":  "CEVA Inc (Israel/US)",
    # ── South Africa ──────────────────────────────────────────────────────
    "NPN":   "Naspers (South Africa)",   # might be OTC only
    "NPSNY": "Naspers Limited (South Africa)",
    "ANGPY": "Anglo American Platinum (South Africa)",
    "AGLXY": "Anglo American (South Africa/UK)",
    # ── Russia (suspended / de-listed — skip) ─────────────────────────────
    # ── Other notable global companies ───────────────────────────────────
    "RDS-A": "Shell (legacy ticker)",    # now SHEL
    "GLNCY": "Glencore plc (Switzerland/UK)",
    "RYAAY": "Ryanair Holdings (Ireland)",
    "WIZZ":  "Wizz Air Holdings (Hungary/UK)",
    "FLTR":  "Flutter Entertainment (Ireland)",
    "INXN":  "InterXion (Netherlands/US)",
    "SPOT":  "Spotify Technology (Sweden/Luxembourg)",
    "DKNG":  "DraftKings (US but notable)",
    "SE":    "Sea Limited (Singapore)",
    "GRAB":  "Grab Holdings (Singapore)",
    "GOTU":  "Gaotu Techedu (China)",
    "OPRA":  "Opera Limited (Norway/China)",
    "GLOB":  "Globant SA (Luxembourg/Argentina)",
    "DESP":  "Despegar.com (Argentina)",
    "ARCO":  "Arcos Dorados Holdings (Argentina)",
    "CAAP":  "Corporación América Airports (Argentina)",
    "TS":    "Tenaris SA (Luxembourg/Argentina)",
    "PAM":   "Pampa Energía (Argentina)",
    "LOMA":  "Loma Negra (Argentina)",
    "SUPV":  "Grupo Supervielle (Argentina)",
    "BIOX":  "Bioceres Crop Solutions (Argentina)",
    "AGRO":  "Adecoagro SA (Luxembourg/Argentina)",
    "VIST":  "Vista Energy (Mexico/Argentina)",
}

# ── US Blue-chip stocks ────────────────────────────────────────────────────
_US_BLUE_CHIPS: dict[str, str] = {
    # ── Mega-cap Tech ─────────────────────────────────────────────────────
    "AAPL":  "Apple Inc",
    "MSFT":  "Microsoft Corporation",
    "NVDA":  "NVIDIA Corporation",
    "AMZN":  "Amazon.com Inc",
    "GOOGL": "Alphabet Inc (Class A)",
    "GOOG":  "Alphabet Inc (Class C)",
    "META":  "Meta Platforms Inc",
    "TSLA":  "Tesla Inc",
    "AVGO":  "Broadcom Inc",
    "ORCL":  "Oracle Corporation",
    # ── Semiconductors ────────────────────────────────────────────────────
    "AMD":   "Advanced Micro Devices",
    "INTC":  "Intel Corporation",
    "QCOM":  "Qualcomm Inc",
    "TXN":   "Texas Instruments",
    "MU":    "Micron Technology",
    "AMAT":  "Applied Materials",
    "LRCX":  "Lam Research",
    "KLAC":  "KLA Corporation",
    "NXPI":  "NXP Semiconductors",
    "ON":    "ON Semiconductor",
    "MCHP":  "Microchip Technology",
    "ADI":   "Analog Devices",
    "MPWR":  "Monolithic Power Systems",
    "ENPH":  "Enphase Energy",
    "WOLF":  "Wolfspeed Inc",
    # ── Software / Cloud ──────────────────────────────────────────────────
    "CRM":   "Salesforce Inc",
    "ADBE":  "Adobe Inc",
    "INTU":  "Intuit Inc",
    "NOW":   "ServiceNow Inc",
    "SNOW":  "Snowflake Inc",
    "PLTR":  "Palantir Technologies",
    "PANW":  "Palo Alto Networks",
    "CRWD":  "CrowdStrike Holdings",
    "ZS":    "Zscaler Inc",
    "FTNT":  "Fortinet Inc",
    "NET":   "Cloudflare Inc",
    "DDOG":  "Datadog Inc",
    "MDB":   "MongoDB Inc",
    "OKTA":  "Okta Inc",
    "HUBS":  "HubSpot Inc",
    "WDAY":  "Workday Inc",
    "VEEV":  "Veeva Systems",
    "ZM":    "Zoom Video Communications",
    "TWLO":  "Twilio Inc",
    "DOCN":  "DigitalOcean Holdings",
    "TTD":   "The Trade Desk",
    "RBLX":  "Roblox Corporation",
    "U":     "Unity Software",
    "APP":   "Applovin Corporation",
    # ── Internet / E-commerce ─────────────────────────────────────────────
    "NFLX":  "Netflix Inc",
    "EBAY":  "eBay Inc",
    "ETSY":  "Etsy Inc",
    "PINS":  "Pinterest Inc",
    "SNAP":  "Snap Inc",
    "LYFT":  "Lyft Inc",
    "UBER":  "Uber Technologies",
    "ABNB":  "Airbnb Inc",
    "BKNG":  "Booking Holdings",
    "EXPE":  "Expedia Group",
    "TRIP":  "TripAdvisor Inc",
    # ── Hardware / Devices ────────────────────────────────────────────────
    "HPQ":   "HP Inc",
    "HPE":   "Hewlett Packard Enterprise",
    "DELL":  "Dell Technologies",
    "STX":   "Seagate Technology",
    "WDC":   "Western Digital",
    "NTAP":  "NetApp Inc",
    "PSTG":  "Pure Storage",
    "ZBRA":  "Zebra Technologies",
    "CDW":   "CDW Corporation",
    "CSCO":  "Cisco Systems",
    "JNPR":  "Juniper Networks",
    "ANET":  "Arista Networks",
    "VIAV":  "Viavi Solutions",
    # ── Financials — Banks ────────────────────────────────────────────────
    "JPM":   "JPMorgan Chase",
    "BAC":   "Bank of America",
    "WFC":   "Wells Fargo",
    "C":     "Citigroup",
    "GS":    "Goldman Sachs",
    "MS":    "Morgan Stanley",
    "USB":   "U.S. Bancorp",
    "PNC":   "PNC Financial Services",
    "TFC":   "Truist Financial",
    "COF":   "Capital One Financial",
    "AXP":   "American Express",
    "DFS":   "Discover Financial Services",
    "SYF":   "Synchrony Financial",
    "ALLY":  "Ally Financial",
    "RF":    "Regions Financial",
    "CFG":   "Citizens Financial Group",
    "HBAN":  "Huntington Bancshares",
    "FITB":  "Fifth Third Bancorp",
    "KEY":   "KeyCorp",
    "MTB":   "M&T Bank",
    "FHN":   "First Horizon",
    "ZION":  "Zions Bancorporation",
    "CMA":   "Comerica",
    "WAL":   "Western Alliance Bancorporation",
    "PACW":  "PacWest Bancorp",
    "SIVB":  "SVB Financial Group",
    # ── Financials — Asset Mgmt / Brokers ────────────────────────────────
    "BLK":   "BlackRock Inc",
    "BX":    "Blackstone Inc",
    "KKR":   "KKR & Co",
    "APO":   "Apollo Global Management",
    "CG":    "Carlyle Group",
    "ARES":  "Ares Management",
    "BEN":   "Franklin Resources",
    "IVZ":   "Invesco Ltd",
    "TROW":  "T. Rowe Price",
    "STT":   "State Street",
    "BK":    "Bank of New York Mellon",
    "NTRS":  "Northern Trust",
    "SCHW":  "Charles Schwab",
    "RJF":   "Raymond James Financial",
    "SF":    "Stifel Financial",
    "LPLA":  "LPL Financial",
    # ── Financials — Payments ─────────────────────────────────────────────
    "V":     "Visa Inc",
    "MA":    "Mastercard Inc",
    "PYPL":  "PayPal Holdings",
    "SQ":    "Block Inc",
    "FIS":   "Fidelity National Information Services",
    "FISV":  "Fiserv Inc",
    "GPN":   "Global Payments",
    "WEX":   "WEX Inc",
    "FOUR":  "Shift4 Payments",
    # ── Financials — Exchanges ────────────────────────────────────────────
    "ICE":   "Intercontinental Exchange",
    "CME":   "CME Group",
    "NDAQ":  "Nasdaq Inc",
    "CBOE":  "Cboe Global Markets",
    "MKTX":  "MarketAxess Holdings",
    # ── Insurance ─────────────────────────────────────────────────────────
    "BRK-B": "Berkshire Hathaway (Class B)",
    "CB":    "Chubb Ltd",
    "AIG":   "American International Group",
    "MET":   "MetLife Inc",
    "PRU":   "Prudential Financial",
    "AFL":   "Aflac Inc",
    "ALL":   "Allstate Corporation",
    "PGR":   "Progressive Corporation",
    "TRV":   "Travelers Companies",
    "HIG":   "Hartford Financial Services",
    "L":     "Loews Corporation",
    "RE":    "Everest Re Group",
    "RNR":   "RenaissanceRe Holdings",
    "AXS":   "Axis Capital Holdings",
    "CINF":  "Cincinnati Financial",
    "WRB":   "W.R. Berkley",
    # ── Healthcare — Pharma ───────────────────────────────────────────────
    "JNJ":   "Johnson & Johnson",
    "PFE":   "Pfizer Inc",
    "MRK":   "Merck & Co",
    "ABBV":  "AbbVie Inc",
    "BMY":   "Bristol-Myers Squibb",
    "LLY":   "Eli Lilly and Company",
    "AMGN":  "Amgen Inc",
    "GILD":  "Gilead Sciences",
    "BIIB":  "Biogen Inc",
    "REGN":  "Regeneron Pharmaceuticals",
    "VRTX":  "Vertex Pharmaceuticals",
    "MRNA":  "Moderna Inc",
    "BNTX":  "BioNTech SE",
    "ALNY":  "Alnylam Pharmaceuticals",
    "SGEN":  "Seagen Inc",
    "INCY":  "Incyte Corporation",
    "EXEL":  "Exelixis Inc",
    "FOLD":  "Amicus Therapeutics",
    # ── Healthcare — Devices / Services ──────────────────────────────────
    "ISRG":  "Intuitive Surgical",
    "MDT":   "Medtronic plc",
    "SYK":   "Stryker Corporation",
    "BSX":   "Boston Scientific",
    "EW":    "Edwards Lifesciences",
    "BDX":   "Becton Dickinson",
    "ZBH":   "Zimmer Biomet Holdings",
    "HOLX":  "Hologic Inc",
    "IDXX":  "IDEXX Laboratories",
    "TFX":   "Teleflex Inc",
    "MMSI":  "Merit Medical Systems",
    "AMED":  "Amedisys Inc",
    "TMO":   "Thermo Fisher Scientific",
    "DHR":   "Danaher Corporation",
    "A":     "Agilent Technologies",
    "IQV":   "IQVIA Holdings",
    "CRL":   "Charles River Laboratories",
    "MTD":   "Mettler-Toledo",
    "WAT":   "Waters Corporation",
    "TECH":  "Bio-Techne Corporation",
    "HSKA":  "Heska Corporation",
    # ── Healthcare — Managed Care ─────────────────────────────────────────
    "UNH":   "UnitedHealth Group",
    "ELV":   "Elevance Health",
    "CVS":   "CVS Health",
    "CI":    "Cigna Group",
    "HUM":   "Humana Inc",
    "MOH":   "Molina Healthcare",
    "CNC":   "Centene Corporation",
    "WCG":   "WellCare Health Plans",
    # ── Consumer Staples ──────────────────────────────────────────────────
    "PG":    "Procter & Gamble",
    "KO":    "Coca-Cola Company",
    "PEP":   "PepsiCo Inc",
    "PM":    "Philip Morris International",
    "MO":    "Altria Group",
    "MDLZ":  "Mondelez International",
    "GIS":   "General Mills",
    "CPB":   "Campbell Soup Company",
    "HRL":   "Hormel Foods",
    "SJM":   "J.M. Smucker",
    "CAG":   "Conagra Brands",
    "MKC":   "McCormick & Company",
    "CLX":   "Clorox Company",
    "CHD":   "Church & Dwight",
    "EL":    "Estee Lauder Companies",
    "KMB":   "Kimberly-Clark",
    "CL":    "Colgate-Palmolive",
    "COTY":  "Coty Inc",
    "ENR":   "Energizer Holdings",
    "SPB":   "Spectrum Brands",
    # ── Consumer Discretionary ────────────────────────────────────────────
    "WMT":   "Walmart Inc",
    "COST":  "Costco Wholesale",
    "TGT":   "Target Corporation",
    "HD":    "Home Depot",
    "LOW":   "Lowe's Companies",
    "MCD":   "McDonald's Corporation",
    "SBUX":  "Starbucks Corporation",
    "YUM":   "Yum! Brands",
    "CMG":   "Chipotle Mexican Grill",
    "DPZ":   "Domino's Pizza",
    "DRI":   "Darden Restaurants",
    "TXRH":  "Texas Roadhouse",
    "BLMN":  "Bloomin' Brands",
    "JACK":  "Jack in the Box",
    "NKE":   "Nike Inc",
    "LULU":  "Lululemon Athletica",
    "VFC":   "VF Corporation",
    "HBI":   "Hanesbrands Inc",
    "PVH":   "PVH Corp",
    "RL":    "Ralph Lauren Corporation",
    "TPR":   "Tapestry Inc",
    "CPRI":  "Capri Holdings",
    "SKX":   "Skechers USA",
    "CROX":  "Crocs Inc",
    "TJX":   "TJX Companies",
    "ROST":  "Ross Stores",
    "BURL":  "Burlington Stores",
    "GPS":   "Gap Inc",
    "ANF":   "Abercrombie & Fitch",
    "AEO":   "American Eagle Outfitters",
    "URBN":  "Urban Outfitters",
    "BBWI":  "Bath & Body Works",
    "M":     "Macy's Inc",
    "JWN":   "Nordstrom Inc",
    "KSS":   "Kohl's Corporation",
    "BBY":   "Best Buy Co",
    "GME":   "GameStop Corp",
    "AUTO":  "AutoNation Inc",
    "AN":    "AutoNation Inc (alt)",
    "KMX":   "CarMax Inc",
    "F":     "Ford Motor Company",
    "GM":    "General Motors",
    "RIVN":  "Rivian Automotive",
    "LCID":  "Lucid Group",
    # ── Energy ────────────────────────────────────────────────────────────
    "XOM":   "ExxonMobil Corporation",
    "CVX":   "Chevron Corporation",
    "COP":   "ConocoPhillips",
    "EOG":   "EOG Resources",
    "PXD":   "Pioneer Natural Resources",
    "OXY":   "Occidental Petroleum",
    "SLB":   "Schlumberger (SLB)",
    "HAL":   "Halliburton Company",
    "PSX":   "Phillips 66",
    "VLO":   "Valero Energy",
    "MPC":   "Marathon Petroleum",
    "BKR":   "Baker Hughes",
    "DVN":   "Devon Energy",
    "HES":   "Hess Corporation",
    "APA":   "APA Corporation",
    "MRO":   "Marathon Oil",
    "CTRA":  "Coterra Energy",
    "FANG":  "Diamondback Energy",
    "PR":    "Permian Resources",
    "SM":    "SM Energy",
    "MTDR":  "Matador Resources",
    "NOV":   "NOV Inc",
    "FTI":   "TechnipFMC",
    "CHK":   "Chesapeake Energy",
    "AR":    "Antero Resources",
    "EQT":   "EQT Corporation",
    "RRC":   "Range Resources",
    "SWN":   "Southwestern Energy",
    "KMI":   "Kinder Morgan",
    "WMB":   "Williams Companies",
    "OKE":   "ONEOK Inc",
    "ET":    "Energy Transfer LP",
    "EPD":   "Enterprise Products Partners",
    "MMP":   "Magellan Midstream Partners",
    "HLX":   "Helix Energy Solutions",
    # ── Industrials ───────────────────────────────────────────────────────
    "GE":    "GE Aerospace",
    "HON":   "Honeywell International",
    "MMM":   "3M Company",
    "CAT":   "Caterpillar Inc",
    "DE":    "Deere & Company",
    "EMR":   "Emerson Electric",
    "ETN":   "Eaton Corporation",
    "ITW":   "Illinois Tool Works",
    "PH":    "Parker-Hannifin",
    "ROK":   "Rockwell Automation",
    "DOV":   "Dover Corporation",
    "FTV":   "Fortive Corporation",
    "IR":    "Ingersoll Rand",
    "TT":    "Trane Technologies",
    "ROP":   "Roper Technologies",
    "KEYS":  "Keysight Technologies",
    "ANSS":  "Ansys Inc",
    "CDNS":  "Cadence Design Systems",
    "SNPS":  "Synopsys Inc",
    "BA":    "Boeing Company",
    "LMT":   "Lockheed Martin",
    "RTX":   "RTX Corporation",
    "NOC":   "Northrop Grumman",
    "GD":    "General Dynamics",
    "LHX":   "L3Harris Technologies",
    "TDG":   "TransDigm Group",
    "HWM":   "Howmet Aerospace",
    "TXT":   "Textron Inc",
    "SPR":   "Spirit AeroSystems",
    "KTOS":  "Kratos Defense & Security",
    "LDOS":  "Leidos Holdings",
    "SAIC":  "Science Applications International",
    "CACI":  "CACI International",
    "MANT":  "ManTech International",
    "UPS":   "United Parcel Service",
    "FDX":   "FedEx Corporation",
    "XPO":   "XPO Inc",
    "ODFL":  "Old Dominion Freight Line",
    "JBHT":  "J.B. Hunt Transport Services",
    "SAIA":  "Saia Inc",
    "ARCB":  "ArcBest Corporation",
    "CHRW":  "C.H. Robinson Worldwide",
    "EXPD":  "Expeditors International",
    "GXO":   "GXO Logistics",
    "NDSN":  "Nordson Corporation",
    "GWW":   "W.W. Grainger",
    "MSC":   "MSC Industrial Direct",
    "FAST":  "Fastenal Company",
    "SNA":   "Snap-on Incorporated",
    "SWK":   "Stanley Black & Decker",
    "MAS":   "Masco Corporation",
    "AOS":   "A.O. Smith",
    "LII":   "Lennox International",
    "CARR":  "Carrier Global",
    "OTIS":  "Otis Worldwide",
    "CSGP":  "CoStar Group",
    "J":     "Jacobs Solutions",
    "PWR":   "Quanta Services",
    "MTZ":   "MasTec Inc",
    "FIX":   "Comfort Systems USA",
    "DY":    "Dycom Industries",
    "PRIM":  "Primoris Services",
    "AYI":   "Acuity Brands",
    "RXO":   "RXO Inc",
    "DXPE":  "DXP Enterprises",
    "HUBB":  "Hubbell Inc",
    "VRSK":  "Verisk Analytics",
    "EFX":   "Equifax Inc",
    "TRI":   "Thomson Reuters",
    "SPGI":  "S&P Global",
    "MCO":   "Moody's Corporation",
    "INFO":  "IHS Markit (merged with SPGI)",
    "MSCI":  "MSCI Inc",
    "FDS":   "FactSet Research Systems",
    # ── Materials ─────────────────────────────────────────────────────────
    "FCX":   "Freeport-McMoRan",
    "NEM":   "Newmont Corporation",
    "AA":    "Alcoa Corporation",
    "CLF":   "Cleveland-Cliffs",
    "NUE":   "Nucor Corporation",
    "STLD":  "Steel Dynamics",
    "RS":    "Reliance Steel & Aluminum",
    "MLM":   "Martin Marietta Materials",
    "VMC":   "Vulcan Materials",
    "LIN":   "Linde plc",
    "APD":   "Air Products and Chemicals",
    "ECL":   "Ecolab Inc",
    "SHW":   "Sherwin-Williams",
    "PPG":   "PPG Industries",
    "RPM":   "RPM International",
    "EMN":   "Eastman Chemical",
    "CE":    "Celanese Corporation",
    "HUN":   "Huntsman Corporation",
    "OLN":   "Olin Corporation",
    "CC":    "Chemours Company",
    "TROX":  "Tronox Holdings",
    "KRO":   "Kronos Worldwide",
    "SLVM":  "Sylvamo Corporation",
    "PKG":   "Packaging Corporation of America",
    "IP":    "International Paper",
    "GPK":   "Graphic Packaging Holding",
    "SEE":   "Sealed Air Corporation",
    "BALL":  "Ball Corporation",
    "ATR":   "AptarGroup",
    # ── Utilities ─────────────────────────────────────────────────────────
    "NEE":   "NextEra Energy",
    "DUK":   "Duke Energy",
    "SO":    "Southern Company",
    "AEP":   "American Electric Power",
    "EXC":   "Exelon Corporation",
    "XEL":   "Xcel Energy",
    "ES":    "Eversource Energy",
    "ETR":   "Entergy Corporation",
    "FE":    "FirstEnergy",
    "D":     "Dominion Energy",
    "PCG":   "PG&E Corporation",
    "AES":   "AES Corporation",
    "CEG":   "Constellation Energy",
    "VST":   "Vistra Corp",
    "NRG":   "NRG Energy",
    "EIX":   "Edison International",
    "AWK":   "American Water Works",
    "WEC":   "WEC Energy Group",
    "CMS":   "CMS Energy",
    "DTE":   "DTE Energy",
    "EVRG":  "Evergy Inc",
    "PNW":   "Pinnacle West Capital",
    "IDA":   "IDACORP Inc",
    "OGE":   "OGE Energy",
    "LNT":   "Alliant Energy",
    "NI":    "NiSource Inc",
    "POR":   "Portland General Electric",
    "AVA":   "Avista Corporation",
    # ── Communication Services ────────────────────────────────────────────
    "T":     "AT&T Inc",
    "VZ":    "Verizon Communications",
    "TMUS":  "T-Mobile US",
    "CMCSA": "Comcast Corporation",
    "CHTR":  "Charter Communications",
    "DIS":   "Walt Disney Company",
    "PARA":  "Paramount Global",
    "WBD":   "Warner Bros. Discovery",
    "FOX":   "Fox Corporation (Class B)",
    "FOXA":  "Fox Corporation (Class A)",
    "NYT":   "New York Times",
    "NWS":   "News Corp",
    "IPG":   "Interpublic Group",
    "OMC":   "Omnicom Group",
    "TTWO":  "Take-Two Interactive",
    "EA":    "Electronic Arts",
    "MTCH":  "Match Group",
    "IAC":   "IAC Inc",
    "ZG":    "Zillow Group",
    "ANGI":  "Angi Inc",
    # ── Real Estate (REITs) ───────────────────────────────────────────────
    "AMT":   "American Tower Corporation",
    "PLD":   "Prologis Inc",
    "EQIX":  "Equinix Inc",
    "CCI":   "Crown Castle Inc",
    "SPG":   "Simon Property Group",
    "O":     "Realty Income Corporation",
    "VICI":  "VICI Properties",
    "WY":    "Weyerhaeuser Company",
    "EXR":   "Extra Space Storage",
    "PSA":   "Public Storage",
    "AVB":   "AvalonBay Communities",
    "EQR":   "Equity Residential",
    "MAA":   "Mid-America Apartment Communities",
    "ESS":   "Essex Property Trust",
    "UDR":   "UDR Inc",
    "CPT":   "Camden Property Trust",
    "VTR":   "Ventas Inc",
    "WELL":  "Welltower Inc",
    "DOC":   "Physicians Realty Trust",
    "MPW":   "Medical Properties Trust",
    "CBRE":  "CBRE Group",
    "JLL":   "Jones Lang LaSalle",
    "ARE":   "Alexandria Real Estate Equities",
    "BXP":   "Boston Properties",
    "SLG":   "SL Green Realty",
    "HIW":   "Highwoods Properties",
    "KIM":   "Kimco Realty",
    "REG":   "Regency Centers",
    "FRT":   "Federal Realty Investment Trust",
    "WRI":   "Weingarten Realty",
    "NNN":   "National Retail Properties",
    "STOR":  "STORE Capital",
    "ADC":   "Agree Realty",
    "STAG":  "Stag Industrial",
    "FR":    "First Industrial Realty Trust",
    "EGP":   "EastGroup Properties",
    "LPT":   "Liberty Property Trust",
    "DLR":   "Digital Realty Trust",
    "COR":   "CoreSite Realty",
    "QTS":   "QTS Realty Trust",
    "IRM":   "Iron Mountain",
    # ── Additional European blue-chips ────────────────────────────────────
    # UK
    "HSBC":  "HSBC Holdings (UK)",
    "BAESY": "BAE Systems (UK)",
    "RYCEY": "Rolls-Royce Holdings (UK)",
    "DEO":   "Diageo plc (UK)",
    "FERG":  "Ferguson Enterprises (UK/US)",
    "WPP":   "WPP plc (UK)",
    "PUK":   "Prudential plc (UK)",
    "SCBFF": "Standard Chartered (UK)",
    "IMBBY": "Imperial Brands (UK)",
    "HCMLY": "Halma plc (UK)",
    "EXPN":  "Experian plc (Ireland/UK)",
    "CMPGY": "Compass Group (UK)",
    # Germany (additional)
    "FMS":   "Fresenius Medical Care (Germany)",
    "FSNUF": "Fresenius SE (Germany)",
    "BNTGY": "Brenntag SE (Germany)",
    "MKKGY": "Merck KGaA (Germany)",
    "HVRRY": "Hannover Re (Germany)",
    "BDRFF": "Beiersdorf AG (Germany)",
    "HENKY": "Henkel AG (Germany)",
    "IFNNY": "Infineon Technologies (Germany)",
    "DBOEY": "Deutsche Boerse (Germany)",
    "TKAGY": "thyssenkrupp AG (Germany)",
    "SXYAY": "Sanofi (alt — France/Germany)",
    # France (additional)
    "DASTY": "Dassault Systèmes (France)",
    "THLLY": "Thales Group (France)",
    "SAFRY": "Safran SA (France)",
    "MGDDY": "Michelin (France)",
    "BOUYY": "Bouygues SA (France)",
    "VCISY": "Vinci SA (France)",
    "LGRDY": "Legrand SA (France)",
    # Switzerland (additional)
    "LZAGY": "Lonza Group (Switzerland)",
    "GVDNY": "Givaudan SA (Switzerland)",
    "SONVY": "Sonova Holding (Switzerland)",
    "JBAXY": "Julius Baer Group (Switzerland)",
    # Netherlands (additional)
    "HEINY": "Heineken NV (Netherlands)",
    "WTKWY": "Wolters Kluwer (Netherlands)",
    "NNGPF": "NN Group (Netherlands)",
    "STLA":  "Stellantis NV (Netherlands/US)",
    "RANJY": "Randstad NV (Netherlands)",
    # Sweden
    "HNNMY": "H&M Group (Sweden)",
    "HXGBY": "Hexagon AB (Sweden)",
    "SDVKY": "Sandvik AB (Sweden)",
    "SKFRY": "SKF AB (Sweden)",
    "ELUXY": "Electrolux AB (Sweden)",
    "ALV":   "Autoliv Inc (Sweden/US)",
    "ASAZY": "Assa Abloy AB (Sweden)",
    "ALFVY": "Alfa Laval AB (Sweden)",
    "BDNNY": "Boliden AB (Sweden)",
    "NIBEF": "Nibe Industrier AB (Sweden)",
    # Denmark (additional)
    "CLPBY": "Coloplast A/S (Denmark)",
    "VWDRY": "Vestas Wind Systems (Denmark)",
    "AMKBY": "A.P. Møller-Mærsk (Denmark)",
    "GMAB":  "Genmab A/S (Denmark)",
    "PANDY": "Pandora A/S (Denmark)",
    "YARIY": "Yara International (Norway)",
    # Norway (additional)
    "DNBHF": "DNB Bank ASA (Norway)",
    "TELNY": "Telenor ASA (Norway)",
    # Finland (additional)
    "KNYJF": "Kone Oyj (Finland)",
    "NRDBY": "Nordea Bank (Finland/Sweden)",
    # Ireland (additional)
    "CRH":   "CRH plc (Ireland/US)",
    "SMFKY": "Smurfit Kappa Group (Ireland)",
    "EDPFY": "EDP — Energias de Portugal",
    # Austria
    "OMVKY": "OMV AG (Austria)",
    "EBKDY": "Erste Group Bank (Austria)",
}


# ── Watchlist builder ──────────────────────────────────────────────────────

def _normalize_ticker(ticker: str) -> str:
    """Yahoo Finance uses '-' where some sources use '.' (e.g. BRK.B → BRK-B)."""
    return str(ticker).strip().replace(".", "-")


def _fetch_sp_index(url: str, label: str) -> dict[str, str]:
    """
    Download one S&P index table from Wikipedia.
    Returns {ticker: company_name}.
    """
    try:
        import pandas as pd  # lazy import — not needed for cache hits

        tables = pd.read_html(url, header=0)
        df = tables[0]

        # Identify ticker and name columns (handles minor Wikipedia variations)
        ticker_col = next(
            (c for c in df.columns if str(c).lower() in ("symbol", "ticker symbol", "ticker")),
            df.columns[0],
        )
        name_col = next(
            (c for c in df.columns if str(c).lower() in ("security", "company", "name")),
            df.columns[1],
        )

        result: dict[str, str] = {}
        for _, row in df.iterrows():
            ticker = _normalize_ticker(row[ticker_col])
            name = str(row[name_col]).strip()
            if ticker and name and ticker.lower() != "nan":
                result[ticker] = name

        logger.info("Fetched %d tickers from %s", len(result), label)
        return result

    except Exception as exc:
        logger.warning("Could not fetch %s from Wikipedia: %s", label, exc)
        return {}


def _load_cache() -> dict[str, str] | None:
    """Return cached watchlist if it exists and is fresh, else None."""
    try:
        if not _CACHE_FILE.exists():
            return None
        data = json.loads(_CACHE_FILE.read_text())
        cached_at = datetime.fromisoformat(data["cached_at"])
        if datetime.utcnow() - cached_at > _CACHE_MAX_AGE:
            logger.info("Watchlist cache is stale; will refresh.")
            return None
        logger.info(
            "Loaded %d tickers from cache (age: %s).",
            len(data["watchlist"]),
            datetime.utcnow() - cached_at,
        )
        return data["watchlist"]
    except Exception as exc:
        logger.warning("Could not read watchlist cache: %s", exc)
        return None


def _save_cache(watchlist: dict[str, str]) -> None:
    try:
        _CACHE_FILE.write_text(
            json.dumps({"cached_at": datetime.utcnow().isoformat(), "watchlist": watchlist},
                       indent=2)
        )
    except Exception as exc:
        logger.warning("Could not write watchlist cache: %s", exc)


def build_watchlist() -> dict[str, str]:
    """
    Build the full watchlist:
      1. Try to load from a local cache (refreshed every 7 days).
      2. If cache is missing/stale, fetch S&P 500 + 400 + 600 from Wikipedia.
      3. Merge with the hardcoded international list.
      4. Persist the merged result to cache.
    """
    cached = _load_cache()
    if cached is not None:
        return cached

    watchlist: dict[str, str] = {}

    for source in _SP_SOURCES:
        watchlist.update(_fetch_sp_index(source["url"], source["label"]))

    # Merge hardcoded lists (don't overwrite S&P names if ticker already present)
    for ticker, name in _INTERNATIONAL.items():
        watchlist.setdefault(ticker, name)
    for ticker, name in _US_BLUE_CHIPS.items():
        watchlist.setdefault(ticker, name)

    if watchlist:
        _save_cache(watchlist)
        logger.info("Watchlist built: %d unique tickers total.", len(watchlist))
    else:
        # Complete fallback: use hardcoded lists only
        watchlist = {**_INTERNATIONAL, **_US_BLUE_CHIPS}
        logger.info("Built watchlist from hardcoded lists: %d tickers.", len(watchlist))

    return watchlist


# ── Module-level WATCHLIST (built once on import) ─────────────────────────
WATCHLIST: dict[str, str] = build_watchlist()
